"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 4


[[blocks]]
type = "prompt"
alignment = "left"
newline = true

    [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "lightBlue"
    background = "transparent"
    
    [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "lightWhite"
    background = "green"

        [blocks.segments.options]
        fetch_status = true
        fetch_upstream_icon = true
        source = "cli"

    [[blocks.segments]]
    type = "status"
    style = "plain"
    foreground = "lightWhite"
    background_templates = ["{{if .Error }}red{{end}}"]
    template = "{{ if .Error }} {{ reason .Code }} {{end}}"


[[blocks]]
alignment = "left"
newline = true
type = "prompt"

    [[blocks.segments]]
    foreground = "blue"
    style = "plain"
    template =  " \u276f"
    type="text"

[transient_prompt]
background = "transparent"
foreground = "blue"
template = " \u276f "
